// Autogenerated from Pigeon (v0.2.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class CBKGlucoseSample;
@class CBKTransmitter;

@interface CBKGlucoseSample : NSObject
@property(nonatomic, strong, nullable) NSNumber * timestamp;
@property(nonatomic, strong, nullable) NSNumber * quantity;
@end

@interface CBKTransmitter : NSObject
@property(nonatomic, copy, nullable) NSString * id;
@end

@interface CBKCallbackApi : NSObject
- (instancetype)initWithBinaryMessenger:(id<FlutterBinaryMessenger>)binaryMessenger;
- (void)newSample:(CBKGlucoseSample*)input completion:(void(^)(NSError* _Nullable))completion;
@end
@protocol CBKApi
-(void)listenForTransmitter:(CBKTransmitter*)input error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void CBKApiSetup(id<FlutterBinaryMessenger> binaryMessenger, id<CBKApi> _Nullable api);

NS_ASSUME_NONNULL_END
